IAM user

diff --git a/IAM/CreateUserandpolicy b/IAM/CreateUserandpolicy
--- a/IAM/CreateUserandpolicy
+++ b/IAM/CreateUserandpolicy
@@ -157,6 +157,30 @@ while true; do
 
         7)
         #  "5. User and group and add user to group"
+        read -p "Enter the name of the Group: " GROUP_NAME
+        if [ -z "$GROUP_NAME" ]; then
+            echo "Group name cannot be empty. Please try again."
+            exit 1
+        fi
+
+        read -p "Enter the name of the IAM User: " USER_NAME
+        if [ -z "$USER_NAME" ]; then
+            echo "Error: IAM User name cannot be empty."
+            exit 1
+        fi
+
+        if ! aws iam list-group --group-name "$GROUP_NAME" > /dev/null 2>&1; then
+            echo "Error: Unable to retrieve Group. Please check if the group exists and you have sufficient permissions."
+            exit 1
+        fi
+
+        if ! aws iam list-users --group-name "$USER_NAME" > /dev/null 2>&1; then
+            echo "Error: Unable to retrieve User. Please check if the User exists and you have sufficient permissions."
+            exit 1
+        fi
+
+
+
 
 
         8)
